export const CoverPageComponentName = 'cover-page-component'
export const CoverPageBlockName = 'cover-page-block'
export const SimplePageBlockName = 'simple-page-block'
export const TextAndAppBlockName = 'text-app-block'
export const AppComponentName = 'app-component'
export const TextAppHeaderComponentName = 'text-app-header-component'
